---
- name: Jenkins build for webserver installation
  hosts: client

  tasks:
    - name: Webserver installation pkg
      package: name=apache2 state=present

    - name: Configuring file
      copy: content="Wow my code got deployed automatically" dest=/var/www/html/index.html

    - name: Service start
      service: name=apache2 state=started
...
